### ISSUE TITLE
needs py3 released ("No module named 'commands'")

### ISSUE THREAD

**Issue by tedder** [zaxe3d/gcode_analyzer#3]
PR #2 is great for python3, but it isn't on pypi. That leave the following error on an install attempt:
```
$ python3 -m pip install gcode_analyzer
[...]
         cwd: /tmp/pip-install-sn4z6egm/gcode-analyzer/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-sn4z6egm/gcode-analyzer/setup.py", line 2, in <module>
        import commands
    ModuleNotFoundError: No module named 'commands'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It installs if I go from master, though that's less than ideal:
```
$ python3 -m pip install git+https://github.com/zaxe3d/gcode_analyzer.git@master
```

**Comment by 0BAB1** [comment]
same issue here
